# Generated by Django 2.2.7 on 2020-01-01 20:29

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(default=core.helpers.getUniqueId, max_length=10, unique=True, verbose_name='Reference ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='core.UserProfile')),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurances',
                'ordering': ['-start_date', 'ref_id'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=core.helpers.LongUniqueId, unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Main Product Image')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('label', models.CharField(blank=True, max_length=10, null=True, verbose_name='Insurance Label')),
                ('label_type', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1, verbose_name='Insurance Label Type')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False, help_text='If the Item should be featured on homepage')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Insurance Type',
                'verbose_name_plural': 'Insurance Types',
                'ordering': ['-timestamp', '-updated', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=core.helpers.getUniqueId, editable=False, help_text='Internal reference ID', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Reference from Paystack', max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction from Paystack', max_length=255, null=True)),
                ('message', models.CharField(blank=True, help_text='Message from Paystack', max_length=255, null=True)),
                ('status', models.CharField(blank=True, help_text='Status string from Paystack', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount Paid in Naira (₦)', max_digits=100)),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Transaction Date')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='insurance.Insurance')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.InsuranceType'),
        ),
    ]
