# Generated by Django 2.2.7 on 2020-01-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insurance',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
