# Generated by Django 2.2.7 on 2020-01-01 19:12

import ckeditor.fields
import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Slider',
                'verbose_name_plural': 'Home Page Sliders',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, help_text='Image size should be 922x731 px', null=True, upload_to='pages/img', verbose_name='Main Image')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('vid_file', models.FileField(blank=True, help_text='Upload Video File', null=True, upload_to='blog/videos')),
                ('youtube_video_id', models.CharField(blank=True, help_text='Youtube Video ID e.g L0I7i_lE5zA. Not Complete Url', max_length=20, null=True)),
                ('extra_info', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('on_navigation', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Main Page',
                'verbose_name_plural': 'Main Pages',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(help_text='Image size is 340x145 px', upload_to='partners')),
                ('website', models.CharField(help_text='Start with http:// or https://', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('info', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Information',
                'verbose_name_plural': 'Site Informations',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=core.helpers.getUniqueId, editable=False, max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Image size is 270x308 px', null=True, upload_to='profile_pics')),
                ('address', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Others', help_text='Gender', max_length=6, null=True)),
                ('dob', models.DateField(blank=True, help_text='Date of Birth', null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payant_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('paystack_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('one_click_purchasing', models.BooleanField(default=False)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'Users Profiles',
                'ordering': ['-reg_date'],
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='Image size is 1900px width and 1267px height', upload_to='sliders/img')),
                ('header', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=300, null=True)),
                ('button_1', models.CharField(blank=True, max_length=50, null=True)),
                ('button_1_url', models.CharField(blank=True, max_length=100, null=True)),
                ('button_2', models.CharField(blank=True, max_length=50, null=True)),
                ('button_2_url', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='core.HomePageSlider')),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Images',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip_code', models.CharField(max_length=100)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
