# Generated by Django 2.2.7 on 2020-01-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='payant_customer_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paystack_customer_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
